---
version: "3.9"

services:
  service-a-core:
    user: app:app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: service-a-core
    hostname: service-a-core
    restart: unless-stopped
    command: >
      sh -c "sleep 2 &&
             alembic -c service_a/src/alembic.ini upgrade head &&
             alembic -c service_a/src/alembic.ini stamp head &&
             python service_a/src/main.py"
    networks:
      - service-a
      - gateway-network
    env_file:
      - ../service_a/src/.env
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    healthcheck:
      test:
        [
          CMD-SHELL,
          wget --no-verbose --tries=1 --spider http://service-a-core:8000
        ]
      interval: 30s
      timeout: 60s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

  service-a-db:
    image: postgres:12.16-alpine3.18
    hostname: service-a-db
    container_name: service-a-db
    restart: unless-stopped
    expose:
      - 5432
    env_file:
      - ../service_a/src/.env
    environment:
      PGDATA: /var/lib/postgresql/data/service-a/pgdata/
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - apgdata-service-a:/var/lib/postgresql/data/service-a/pgdata/
    networks:
      - service-a
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"

networks:
  service-a:
    driver: bridge
  gateway-network: 
    external: true
volumes:
  apgdata-service-a: {}
