"""add_extra_fields_to_book

Revision ID: e33a1cf85a27
Revises: 1652762a51cb
Create Date: 2024-08-07 06:11:56.959639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e33a1cf85a27"
down_revision: Union[str, None] = "1652762a51cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

bookgenre = postgresql.ENUM(
    "fiction", "love_story", "crime", name="bookgenre", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bookgenre.create(op.get_bind(), checkfirst=True)

    op.add_column("book", sa.Column("genre", bookgenre, nullable=False))
    op.add_column("book", sa.Column("extra_genre", bookgenre, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "extra_genre")
    op.drop_column("book", "genre")
    # ### end Alembic commands ###
