"""add_author_model

Revision ID: 85252c9de65f
Revises: e33a1cf85a27
Create Date: 2024-08-20 07:56:37.353768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85252c9de65f"
down_revision: Union[str, None] = "e33a1cf85a27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_author_id"), "author", ["id"], unique=False)
    op.add_column("book", sa.Column("author_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_book_author_id"), "book", ["author_id"], unique=False
    )
    op.create_foreign_key(
        None, "book", "author", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "book", type_="foreignkey")
    op.drop_index(op.f("ix_book_author_id"), table_name="book")
    op.drop_column("book", "author_id")
    op.drop_index(op.f("ix_author_id"), table_name="author")
    op.drop_table("author")
    # ### end Alembic commands ###
